name: arkhelper

on:
  workflow_dispatch:
  push:
    paths:
      - 'akhelper/**'
      - '.github/workflows/arkhelper.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Metadata for alpine images
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.actor }}/arkhelper
          flavor: latest=true

      - name: Login to registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: akhelper/
          file: akhelper/Dockerfile
          platforms: linux/amd64, linux/386, linux/arm64, linux/arm/v7, linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
